- name: Install psycopg2 system package (Ubuntu/Debian)
  apt:
    name: python3-psycopg2
    state: present
  become: yes

- name: Install psycopg2-binary with pip
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3
  become: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
  become: yes
  notify: Start PostgreSQL

- name: Create PostgreSQL User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
    state: present
